In [1]:
import pandas as pd

## Data Cleaning and Understanding

In [2]:
df = pd.read_csv('data/dauerzaehlstellen.csv', sep=';', encoding='latin-1')
df.head()

,JAHR,MONAT,ZNR,ZNAME,STRTYP,STRNR,RINAME,FZTYP,DTVMS,DTVMF,DTVMO,DTVDD,DTVFR,DTVSA,DTVSF,TVMAX,TVMAXT
0,2025,MÄRZ,1075,Reichsbrücke,B,8,Leopoldstadt,Kfz,26977,28544,28550,28126,29791,24767,22602,47760,"Do,27.03."
1,2025,MÄRZ,1075,Reichsbrücke,B,8,Leopoldstadt,LkwÄ,1674,1688,1846,1590,1782,1657,1634,5081,"So,30.03."
2,2025,MÄRZ,1075,Reichsbrücke,B,8,Donaustadt,Kfz,16067,17416,16563,17705,17615,14382,12089,19871,"Do,20.03."
3,2025,MÄRZ,1075,Reichsbrücke,B,8,Donaustadt,LkwÄ,282,365,371,381,310,121,96,462,"Di,25.03."
4,2025,MÄRZ,1075,Reichsbrücke,B,8,Gesamt,Kfz,43044,45960,45112,45831,47406,39150,34691,66394,"Do,27.03."

### Drop columns and rows not needed for the analysis

- `ZNR` and `ZNAME` identify the measurement station, with one being an int and the other a string. The columns are redundant, so drop `ZNAME`.
- Keep only `DTVMS` and drop the rest of the traffic count columns since only interested in the average, daily traffic counts for all days of the week.
- Select rows where `FZTYP` == `Kfz` since only want to work with total traffic counts, then drop the column.

In [3]:
drop_cols = ['ZNAME', 'DTVMF', 'DTVMO', 'DTVDD', 'DTVFR', 'DTVSA', 'DTVSF', 'TVMAX', 'TVMAXT']
df = df.drop(columns=drop_cols)
df = df[df['FZTYP'] == 'Kfz']
df = df.drop(columns=['FZTYP'])
df = df.reset_index(drop=True)

Convert MONAT column from string to int.

In [4]:
df['MONAT'] = df['MONAT'].str.rstrip('.')
df['MONAT'] = df['MONAT'].str.lower()

monat_map = {'jan': 1, 'feb' : 2,  'märz': 3,  'april': 4,
             'mai': 5, 'juni': 6,  'juli': 7,  'aug'  : 8,
             'sep': 9, 'okt' : 10, 'nov' : 11, 'dez'  : 12}

df['MONAT'] = df['MONAT'].map(monat_map)

In [5]:
df.head()

   JAHR  MONAT   ZNR STRTYP  STRNR        RINAME  DTVMS
0  2025      3  1075      B      8  Leopoldstadt  26977
1  2025      3  1075      B      8    Donaustadt  16067
2  2025      3  1075      B      8        Gesamt  43044
3  2025      3  1078      B    221     Wienzeile  36497
4  2025      3  1078      B    221    Stadthalle  32686